### ISSUE TITLE
Feature request: econftool syntax check of a fragment

### ISSUE THREAD

**Issue by maage** [openSUSE/libeconf#159]
Add new feature where econftool reads a named fragment and checks syntax, exit 0 if okay, exit 1 if not.

```
syntax reads filename <filename> and checks syntax.
```

This feature would be useful in ansible to do validate for any file parsed by libeconf. Something like:

```
- name: My login.defs
  ansible.builtin.copy:
    content: |
       ... my inline login.defs content too easy to mess up yaml / ansible variables and such ...
    dest: /etc/login.defs
    validate: econftool syntax %s
```
